CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    serial_number INT NOT NULL UNIQUE,
    rfid_tag VARCHAR(255) NOT NULL UNIQUE,
    item_name VARCHAR(255) NOT NULL,
    createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);